version: "3"
services:
  points-api:
    build: .
    image: osmbrowser/points-api
    environment:
      - BUGSNAG_API_KEY
      - DATABASE_URL=ecto://osm:osm@postgres/osm
      - MIX_ENV
    links:
      - postgres
  postgres:
    image: mdillon/postgis:10-alpine
    environment:
      - POSTGRES_USER=osm
      - POSTGRES_PASSWORD=osm
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
