version: "3"
services:
  points-api:
    environment:
      - MIX_ENV=dev
    volumes:
      - .:/usr/src/points-api
    ports:
      - "4000:4000"
  postgres:
    ports:
      - "5432:5432"
  pgweb:
    image: sosedoff/pgweb
    environment:
      - DATABASE_URL=postgres://osm:osm@postgres:5432/postgres?sslmode=disable
    links:
      - postgres
    ports:
      - "4001:8081"
