apiVersion: v1
kind: Secret
metadata:
  name: {{ template "points-api.fullname" . }}
  labels:
    app: {{ template "points-api.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  DB_USER: {{ .Values.postgresql.postgresUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
