apiVersion: v1
kind: Secret
metadata:
  name: {{ template "points-api.fullname" . }}
  labels:
    app: {{ template "points-api.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  db-user: {{ .Values.postgresql.postgresUser | b64enc | quote }}
  db-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
