version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5
      - image: osmbrowser/postgis
        environment:
          POSTGRES_USER: osm
          POSTGRES_PASSWORD: osm
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
